### ISSUE TITLE
小米推送点击通知栏无法开启应用

### ISSUE THREAD

**Issue by jingzhiwei0314** [rongcloud/rongcloud-react-native-imlib#21]

**Comment by jingzhiwei0314** [comment]
06-10 14:48:06.409 10939-10939/com.sense.firmailpro E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sense.firmailpro, PID: 10939
    java.lang.RuntimeException: Unable to start receiver cn.rongcloud.imlib.react.RCPushReceiver: android.content.ActivityNotFoundException: No Activity found to handle Intent { dat=rong://com.sense.firmailpro/push_message?targetId=&pushContent=alert&pushData=&extra={}&isFromPush=true flg=0x10000000 pkg=com.sense.firmailpro }
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2739)
        at android.app.ActivityThread.access$1800(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5442)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
     Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { dat=rong://com.sense.firmailpro/push_message?targetId=&pushContent=alert&pushData=&extra={}&isFromPush=true flg=0x10000000 pkg=com.sense.firmailpro }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1514)
        at android.app.ContextImpl.startActivity(ContextImpl.java:687)
        at android.app.ContextImpl.startActivity(ContextImpl.java:669)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:341)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:341)
        at io.rong.push.notification.PushMessageReceiver.handleNotificationClickEvent(PushMessageReceiver.java:107)
        at io.rong.push.notification.PushMessageReceiver.onReceive(PushMessageReceiver.java:51)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2732)
        at android.app.ActivityThread.access$1800(ActivityThread.java:153) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5442) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by qiuxiang** [comment]
在看怎么解决

**Comment by jingzhiwei0314** [comment]
我在网上找到了一招解决方案，但可能不是最优的方案，在rongcloud-react-native-imlib层RCPushReceiver类中的onNotificationMessageClicked通知点击回调函数重写：


    @Override
    public boolean onNotificationMessageClicked(Context context, PushType pushType, PushNotificationMessage message) {
        Log.i("RCPushReceiver", "RCPushReceiver onNotificationMessageClicked pushType -> " + pushType);
//        if (eventEmitter != null) {
//            eventEmitter.emit("rcimlib-push-clicked", Convert.toJSON(message, pushType));
//            return true;
//        }

        Intent intent = new Intent();
        intent.setClassName(context.getPackageName(),   "XXX.XXX.XXX.MainActivity");
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_SINGLE_TOP);
        context.startActivity(intent);
        return true;
    }
