### ISSUE TITLE
接入华为推送出错，请求帮助

### ISSUE THREAD

**Issue by DwyaneWadeee** [rongcloud/rongcloud-react-native-imlib#44]
我在Application的onCreate()里支持华为推送。
PushConfig config = new PushConfig.Builder()
            .enableHWPush(true).build();
RongPushClient.setPushConfig(config);

软件运行报错：
java.lang.ClassCastException: com.facebook.react.bridge.ReactApplicationContext cannot be cast to android.app.Application
        at io.rong.push.platform.hms.HWPush$1.run(HWPush.java:27)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

定位到这个rn库里的jar包里的HWPush文件
                HMSAgent.init((Application)context);
类型转换出错，请求帮助，告知解决方法，谢谢

**Comment by DwyaneWadeee** [comment]
没人吗，急

**Comment by qiuxiang** [comment]
rn 提供的 application 不能用在华为 push 的初始化，稍等我看看，reactApplication 应该是能访问到 android application 的

**Comment by qiuxiang** [comment]
`reactContext.getApplicationContext()`
