### ISSUE TITLE
启动demo报错

### ISSUE THREAD

**Issue by jiaojunying** [rongcloud/rongcloud-react-native-imlib#58]
Loading dependency graph, done.
error: bundling failed: Error: While trying to resolve module `rongcloud-react-native-imlib` from file `E:\YWKJ\Demo\rongcloud-react-native-imlib-master\example\index.js`, the package `E:\YWKJ\Demo\rongcloud-react-native-imlib-master\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`E:\YWKJ\Demo\rongcloud-react-native-imlib-master\lib\js`. Indeed, none of these files exist:

  * E:\YWKJ\Demo\rongcloud-react-native-imlib-master\lib\js(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * E:\YWKJ\Demo\rongcloud-react-native-imlib-master\lib\js\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ResolutionRequest.resolveDependency (E:\YWKJ\Demo\rongcloud-react-native-imlib-master\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:65:15)
    at DependencyGraph.resolveDependency (E:\YWKJ\Demo\rongcloud-react-native-imlib-master\node_modules\metro\src\node-haste\DependencyGraph.js:282:16)
    at Object.resolve (E:\YWKJ\Demo\rongcloud-react-native-imlib-master\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at dependencies.map.result (E:\YWKJ\Demo\rongcloud-react-native-imlib-master\node_modules\metro\src\DeltaBundler\traverseDependencies.js:426:31)
    at Array.map (<anonymous>)
    at resolveDependencies (E:\YWKJ\Demo\rongcloud-react-native-imlib-master\node_modules\metro\src\DeltaBundler\traverseDependencies.js:423:18)
    at E:\YWKJ\Demo\rongcloud-react-native-imlib-master\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (E:\YWKJ\Demo\rongcloud-react-native-imlib-master\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
    at _next (E:\YWKJ\Demo\rongcloud-react-native-imlib-master\node_modules\metro\src\DeltaBundler\traverseDependencies.js:107:9)
 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 1.1% (29/285), failed.

::ffff:192.168.1.168 - - [05/Dec/2019:09:23:07 +0000] "GET /index.bundle?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.12.1"

**Comment by qiuxiang** [comment]
demo 需要运行
```
yarn add typescript
yarn build
```
